# Global Values
repoUrl: 'https://github.com/chickencordonbleu/eks-blueprints-add-ons.git'
targetRevision: HEAD
region: ''
account: ''
clusterName: ''
destinationServer: ''
argoNamespace: ''
argoProject: ''

# AWS Load Balancer Controller Values
awsLoadBalancerController:
  enable: true
  createNamespace: true
  serviceAccountName:
  podDisruptionBudget:
    maxUnavailable: 1
  respectIgnoreDifferences: true
  ignoreDifferences:
  - group: ""
    kind: "Secret"
    jsonPointers:
    - /data
  - group: "admissionregistration.k8s.io"
    kind: "MutatingWebhookConfiguration"
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - group: "admissionregistration.k8s.io"
    kind: "ValidatingWebhookConfiguration"
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'

# Cert Manager Values
certManager:
  enable: true
  createNamespace: true
  serviceAccountName:

# Nginx Values
ingressNginx:
  enable: false
  createNamespace: true

# Grafana default Values
grafana:
  enable: true
  serviceAccount:
    create: false

# Karpenter Values
karpenter:
  enable: true
  createNamespace: true
  serviceAccountName:
  controllerClusterEndpoint:
  awsDefaultInstanceProfile:
  interruptionQueueName:

# Metrics Server Values
metricsServer:
  enable: true

# Prometheus Values
prometheus:
  enable: true
  createNamespace: true
  serviceAccountName:
  roleArn:
  ampWorkspaceUrl:
  server:
    service:
      type: LoadBalancer

# Metrics Server Values
sparkOperator:
  enable: false
  createNamespace: true